clientes = {
    # RENAN
    'NEONATURE': {'url': 'https://trello.com/c/isHNYjF2/114-neonature-r2090?search_id=74ad3470-fb40-4cc4-a570-97f0db795b2b', 'responsável': 'RENAN', 'CD': 'SC'},
    'GWS': {'url': 'https://trello.com/c/K9zCVuZt/275-gws-plano-r2090?search_id=073dec2d-3460-4ca9-9207-95d6539584cf', 'responsável': 'RENAN', 'CD': 'SC'},
    'VANGUARDA': {'url': 'https://trello.com/c/u4YCEdLY/127-vanguarda-plano-r2500?search_id=97d5c0e1-ae35-4bbc-afb8-29d239a6ea64', 'responsável': 'RENAN', 'CD': 'SC'},
    'ASTROMIC': {'url': 'https://trello.com/c/oxZjMuLo/291-astromic-plano-r2400?search_id=71364682-7855-484a-8ff6-7d4dad2cb375', 'responsável': 'RENAN', 'CD': 'SC'},
    'NUTRAVITA': {'url': 'https://trello.com/c/Q4exWUKV/390-nutravita-plano-r2400?search_id=65bf5c79-6b54-44e4-a442-437c305cebe0', 'responsável': 'RENAN', 'CD': 'SC'},
    'NEURO BETES': {'url': 'https://trello.com/c/vX4wuEZp/356-bmf-neuro-betes-r-2600?search_id=ca7aa835-12a5-473a-a44d-6fd14ca26ffc', 'responsável': 'RENAN', 'CD': 'SC'},
    'SUPER INFOPRODUCTS': {'url': 'https://trello.com/c/AOBYIYEA/389-super-infoproducts?search_id=2625cd2f-def2-4122-bdef-467b5507e79b', 'responsável': 'RENAN', 'CD': 'SC'},
    'LUNO': {'url': 'https://trello.com/c/KHseD7gY/260-luno-plano-r2290?search_id=836d4098-b463-45bd-bd7b-306495b2af4e', 'responsável': 'RENAN', 'CD': 'ES'},
    'MF COSMETICS': {'url': 'https://trello.com/c/CS4hXbmO/344-cosmetics-mf-plano-r2600?search_id=e6e987a8-016d-44bb-87f9-a1bd87f8f5c7', 'responsável': 'RENAN', 'CD': 'SP'},
    'RADT': {'url': 'https://trello.com/c/fxARvbZ7/307-radt-mkt-plano-r2600?search_id=2d453c9d-df6a-4365-9aff-e0a37ec3f1a9', 'responsável': 'RENAN', 'CD': 'SP'},
    'DESAGITA': {'url': 'https://trello.com/c/qFGMCBqq/3-desagita-plano-custo30?search_id=0f0a321d-aa83-47cf-b2e3-f407ab7175f6', 'responsável': 'RENAN', 'CD': 'SP'},
    'DIABETINA': {'url': 'https://trello.com/c/bQclfE4j/333-diabetina-gummies-plano-r-2600?search_id=d6803694-8484-4252-b7ab-04aa72facf77', 'responsável': 'RENAN', 'CD': 'SP'},
    'SAUDE FITNESS': {'url': 'https://trello.com/c/B4u0OrAl/319-saude-fitness-vitamax-plano-r2600?search_id=3edadae2-554b-4a5c-bf79-22da50d4063f', 'responsável': 'RENAN', 'CD': 'SP'},
    'REFORMAMIX': {'url': 'https://trello.com/c/BFvlxCNw/296-reformamix-plano-r2600?search_id=cf98d4b3-8e64-4526-9eee-296cc9906e8c', 'responsável': 'RENAN', 'CD': 'SP'},
    'NUTRAFIX': {'url': 'https://trello.com/c/4odNGonN/392-nutrafix?search_id=ebf58af8-bd29-4125-aee7-4ae7146feb5a', 'responsável': 'RENAN', 'CD': 'SP'},
    # NICOLI
    'MS LABS':	{'url':'https://trello.com/c/Ckiuhmcb/71-bhever-ms-labs-pac-2200-mini-2100?search_id=501dab04-f3bb-4ae8-96d3-66c121b83801', 'responsável': 'NICOLI', 'CD':'SC'},
    'AIRGLOW':	{'url':'https://trello.com/c/fdmPxAJk/334-airglow-plano-r2600?search_id=2ac0894d-cee3-4cf8-a094-8df48460e259', 'responsável': 'NICOLI', 'CD':'SC'},
    'AFINE':	{'url':'https://trello.com/c/CoqfTW0y/284-afine-plano-r2500?search_id=7c4e1296-bd93-43c1-80fe-6c7012619103', 'responsável': 'NICOLI', 'CD':'SC'},
    'INFODIGITAL':	{'url':'https://trello.com/c/vfuCh21Z/364-infodigitalwin-marketing-direto-ltda-plano-r2600?search_id=169a061b-b935-4872-8e4d-79af05147dc4', 'responsável': 'NICOLI', 'CD':'SC'},
    'VFARM':	{'url':'https://trello.com/c/AoSMjzXM/44-vfarm-plano-custo30?search_id=d62b690f-5347-4eee-871a-38af946db368', 'responsável': 'NICOLI', 'CD':'SP'},
    'THE SELLER':	{'url':'https://trello.com/c/UOetajuJ/391-the-seller?search_id=de49ab66-22b7-4d6c-9ac3-f61a7ed9b922', 'responsável': 'NICOLI', 'CD':'SP'},
    'DETOX BLACK':	{'url':'https://trello.com/c/bPsZF56r/348-detox-black-plano-r2600?search_id=cfd0026f-f224-461e-82f4-a9e19d4b7768', 'responsável': 'NICOLI', 'CD':'SP'},
    'HM7 / MSH':	{'url':'https://trello.com/c/OQOPzuyJ/313-mhs-prostilm4n-plano-r2600?search_id=c7356bd1-ee3e-4875-9dd4-40e17177e5b3', 'responsável': 'NICOLI', 'CD':'SP'},
    'MOMPEAN':	{'url':'https://trello.com/c/H0EanXDK/295-mompean-plano-r2600?search_id=1187ef5b-1971-4928-b06b-ec82c7795da2', 'responsável': 'NICOLI', 'CD':'SP'},
    'VGJ':	{'url':'https://trello.com/c/fy8lLKes/282-vgj-new-upgrade-plano-r2500?search_id=127f582b-0115-4b88-866c-e7f5748b3a9c', 'responsável': 'NICOLI', 'CD':'SP'},
    # DIOGO
    'VEDA':	{'url':'https://trello.com/c/NXjb1jGQ/321-veda-saúde-r2600', 'responsável': 'DIOGO', 'CD':'SP'},
    'GREEN LIME':	{'url':'https://trello.com/c/AQz3Sw4l/131-green-lime', 'responsável': 'DIOGO', 'CD':'SP'},
    'MADEYCHA':	{'url':'https://trello.com/c/r8x4bkJb/166-madeycha-plano-r2700', 'responsável': 'DIOGO', 'CD':'SP'},
    'KENEDY':	{'url':'https://trello.com/c/muOXzwvb/302-kenedy-plano-r2600', 'responsável': 'DIOGO', 'CD':'SP'},
    'VITAPHARMA':	{'url':'https://trello.com/c/OTucM1Dh/192-vitapharma-testonox-plano-r2800', 'responsável': 'DIOGO', 'CD':'SP'},
    'DIGITAL SPACE':	{'url':'https://trello.com/c/dhu8irD3/310-digital-space-plano-r2600', 'responsável': 'DIOGO', 'CD':'SP'},
    'RISE UP':	{'url':'https://trello.com/c/aNbk9UxR/355-rise-up', 'responsável': 'DIOGO', 'CD':'SP'},
    'HOGS NUTRA':	{'url':'https://trello.com/c/ZNatlBYQ/336-hogs-nutra-ltda-plano-r2600', 'responsável': 'DIOGO', 'CD':'SC'},
    'OCULAR POWER':	{'url':'https://trello.com/c/q9N9HjH4/303-ocular-power-plano-r2000', 'responsável': 'DIOGO', 'CD':'SC'},
    'APICE':	{'url':'https://trello.com/c/JqzhyFOd/218-ápice-suplementos-plano-r2700', 'responsável': 'DIOGO', 'CD':'SC'},
    'LIBIDUX':	{'url':'https://trello.com/c/64yrYNG0/379-libidux-plano-r2600', 'responsável': 'DIOGO', 'CD':'SC'},
    'ENERGIX':	{'url':'https://trello.com/c/8U1kJMCP/382-lion-midia-energix-plano-r2600', 'responsável': 'DIOGO', 'CD':'SC'},
    'PCJ':	{'url':'https://trello.com/c/0ndSPCh7/369-pcj-company', 'responsável': 'DIOGO', 'CD':'SC'},
    'LOJA EXPERIENCE':	{'url':'https://trello.com/c/2GDeZFVs/283-loja-experience-plano-r2600', 'responsável': 'DIOGO', 'CD':'ES'},
    # kYMBERLI
    'COLLAB':	{'url':'https://trello.com/c/42ccbnt3/328-collab-fortal-plano-r2600', 'responsável': 'KYM', 'CD':'SC'},
    'ON LIMITLESS':	{'url':'https://trello.com/c/6KJtwocL/330-on-limitless-plano-r2600', 'responsável': 'KYM', 'CD':'SC'},
    'VITTER':	{'url':'https://trello.com/c/2Qy1Z3OM/349-vitter-plano-r2600', 'responsável': 'KYM', 'CD':'SC'},
    'MWF':	{'url':'https://trello.com/c/I4uppHkd/377-mwf-plano-r-2600', 'responsável': 'KYM', 'CD':'SC'},
    'PFE GROUP':	{'url':'https://trello.com/c/2pGRrRKh/337-pfe-group-caps-plano-r2500', 'responsável': 'KYM', 'CD':'SC'},
    'VITALKA':	{'url':'https://trello.com/c/JjFwNcDm/368-vitalka-renovabio', 'responsável': 'KYM', 'CD':'SC'},
    'VITTALABS':	{'url':'https://trello.com/c/FyjHwQG5/317-vittalabs-plano-r2600', 'responsável': 'KYM', 'CD':'SC'},
    'PORTO 71':	{'url':'https://trello.com/c/FVbcyu3S/384-porto-71-plano-r2600', 'responsável': 'KYM', 'CD':'SC'},
    'KL DIGITAL':	{'url':'https://trello.com/c/tIcgfqQl/352-kl-digital-superglico-plano-r2600', 'responsável': 'KYM', 'CD':'SP'},
    'SPW DIGITAL':	{'url':'https://trello.com/c/jFbwfYic/324-spw-digital-plano-r2600', 'responsável': 'KYM', 'CD':'SP'},
    'DLS VAREJO':	{'url':'https://trello.com/c/CfEHIGEs/345-dls-varejo-plano-r2600', 'responsável': 'KYM', 'CD':'SP'},
    'DTX':	{'url':'https://trello.com/c/p1bEhPiM/316-dtx-r2600', 'responsável': 'KYM', 'CD':'SP'},
    'JOARLEY SECHER':	{'url':'https://trello.com/c/bsPq34ZX/318-joarley-secher-plano-r2600', 'responsável': 'KYM', 'CD':'SP'},
    'CAVALLARO':	{'url':'https://trello.com/c/8WSrs100/354-cavallaro-media', 'responsável': 'KYM', 'CD':'SP'},
    'NUTRALIV':	{'url':'https://trello.com/c/9ngu6Xmp/385-nutraliv-plano-r-2600', 'responsável': 'KYM', 'CD':'SP'},
    'RENEW / SUNNY':	{'url':'https://trello.com/c/eiIBhi4q/292-renew-sunny-vitaminas-plano-r2600', 'responsável': 'KYM', 'CD':'SP'},
    # THAIS
    'TOUCH BRASIL':	{'url':'https://trello.com/c/wUfNaBt4/249-touch-brasil-plano-r2500', 'responsável': 'THAIS', 'CD':'SP'},
    'GOLD CLUB':	{'url':'https://trello.com/c/2SzzHw5T/4-gold-club', 'responsável': 'THAIS', 'CD':'SP'},
    'AFROCARE':	{'url':'https://trello.com/c/u0GYZzJY/388-afrocare-plano-r2600', 'responsável': 'THAIS', 'CD':'SP'},
    'COIMBRA & FILHO':	{'url':'https://trello.com/c/tNI9ZugE/363-coimbra-e-filho-plano-r-2600', 'responsável': 'THAIS', 'CD':'SP'},
    'DANNS':	{'url':'https://trello.com/c/lDKLVrZD/360-danns-plano-r2600', 'responsável': 'THAIS', 'CD':'SP'},
    'TM / XP':	{'url':'https://trello.com/c/1kJfPQJB/11-tm-xp-life-plano-custo-20-fechamento-semanal-toda-terça', 'responsável': 'THAIS', 'CD':'SP'},
    'ARI FLORA':	{'url':'https://trello.com/c/jTIu8t0c/367-ari-flora-ltda-plano-r', 'responsável': 'THAIS', 'CD':'SP'},
    'MY SIS':	{'url':'https://trello.com/c/8QPeO5jQ/380-my-sis-plano-r2600', 'responsável': 'THAIS', 'CD':'SP'},
    'DK DIGITAL':	{'url':'https://trello.com/c/yeLQa0UZ/347-dk-digital-plano-r2600', 'responsável': 'THAIS', 'CD':'SP'},
    'ALIVIO MAIS':	{'url':'https://trello.com/c/x4K66Dfs/320-alivio-mais-plano-r2600', 'responsável': 'THAIS', 'CD':'SP'},
    'LOG DIGITAL':	{'url':'https://trello.com/c/FzXaDlOW/361-log-digital-plano-r2600', 'responsável': 'THAIS', 'CD':'SP'},
    'SUPER GORILA':	{'url':'https://trello.com/c/qBTAkd4A/370-super-gorila', 'responsável': 'THAIS', 'CD':'SP'},
    'LUAROL':	{'url':'https://trello.com/c/siPdsx1o/225-luarol-plano-r2600', 'responsável': 'THAIS', 'CD':'SC'},
    'GRUPO B CRIAÇÕES':	{'url':'https://trello.com/c/FbAA6ySk/315-grupo-b-criações-plano-r2600', 'responsável': 'THAIS', 'CD':'SC'},
    'HP ADS':	{'url':'https://trello.com/c/NpYqg6T3/381-hp-ads-plano-r2600', 'responsável': 'THAIS', 'CD':'ES'},
    # FELIPE
    'ULTRAVITA':	{'url':'https://trello.com/c/ddYXeMtl/359-ultravita-slim-algas-plano-r2600', 'responsável': 'FELIPE', 'CD':'SP'},
    'IONSCAP':	{'url':'https://trello.com/c/X0Tp8Rnb/162-ionscap-nutraceuticos', 'responsável': 'FELIPE', 'CD':'SP'},
    'ARROJO':	{'url':'https://trello.com/c/qGspKpPs/294-arrojo-plano-r2600', 'responsável': 'FELIPE', 'CD':'SP'},
    'LIFENED':	{'url':'https://trello.com/c/f0jM0n0u/7-lifened-custo20', 'responsável': 'FELIPE', 'CD':'SP'},
    '9RS':	{'url':'https://trello.com/c/pclzZBYj/175-9rs-e-chm-2800', 'responsável': 'FELIPE', 'CD':'SP'},
    'SEAVE':	{'url':'https://trello.com/c/AFYWH9oR/151-seave', 'responsável': 'FELIPE', 'CD':'SP'},
    'T3':	{'url':'https://trello.com/c/mVnxO7lg/10-t3-marketing-plano-custo30', 'responsável': 'FELIPE', 'CD':'SP'},
    'SMART TRADING':	{'url':'https://trello.com/c/P2ipSxmb/76-smart-tranding-plano-r2800', 'responsável': 'FELIPE', 'CD':'SP'},
    'NUTRA 8D':	{'url':'https://trello.com/c/OjDCvo81/251-nutra-8d', 'responsável': 'FELIPE', 'CD':'SP'},
    'JEI LOWISK':	{'url':'https://trello.com/c/2mexzzan/261-jei-lowisk-plano-r2500', 'responsável': 'FELIPE', 'CD':'SP'},
    'ESCALONANDO':	{'url':'https://trello.com/c/LWhLbDdd/301-escalonando-plano-r2600', 'responsável': 'FELIPE', 'CD':'SP'},
    'SIX':	{'url':'https://trello.com/c/qZ1JRFge/204-six-produtos-plano-r2600', 'responsável': 'FELIPE', 'CD':'SC'},
    'BIOCARE':	{'url':'https://trello.com/c/VJQJc8IA/102-biocare-plano-custo-30', 'responsável': 'FELIPE', 'CD':'SC'},
    # GABRIELA
    'MENOVIDA':	{'url':'https://trello.com/c/01itq0nA/252-menovida-funnel-x-plano-r1800', 'responsável': 'GABRIELA', 'CD':'SC'},
    'GRIT ADS':	{'url':'https://trello.com/c/Rhs6vMso/366-grit-ads', 'responsável': 'GABRIELA', 'CD':'SC'},
    'AMS':	{'url':'https://trello.com/c/EHzy9Uz2/217-ams-produtos-naturais-impera-produtos-naturais-custo-30', 'responsável': 'GABRIELA', 'CD':'SC'},
    'ACTIVE':	{'url':'https://trello.com/c/Kb0STuxk/326-active-solutions-plano-r2600', 'responsável': 'GABRIELA', 'CD':'SC'},
    'GF':	{'url':'https://trello.com/c/Pi1lqOXQ/329-gf-suplementos-plano-r2600', 'responsável': 'GABRIELA', 'CD':'SP'},
    'HEBE':	{'url':'https://trello.com/c/tNeMHdKX/293-hebe-800k-plano-r2200', 'responsável': 'GABRIELA', 'CD':'SP'},
    'TORRES':	{'url':'https://trello.com/c/rRvri6wk/312-torres-seven-produtos-naturais-plano-r2600', 'responsável': 'GABRIELA', 'CD':'SP'},
    'LUMA':	{'url':'https://trello.com/c/T6wNdPV0/314-luma-natural-firgon-plano-r2600', 'responsável': 'GABRIELA', 'CD':'SP'},
    'MM DIGITAL':	{'url':'https://trello.com/c/Rik605oS/340-mm-digital-plano-r2600', 'responsável': 'GABRIELA', 'CD':'SP'},
    'LCAPS':	{'url':'https://trello.com/c/S9WlL0D8/358-lcaps-plano-r2600', 'responsável': 'GABRIELA', 'CD':'SP'},
    'FABRICA PREMIUM':	{'url':'https://trello.com/c/aS6oNjuE/373-fabrica-premium-ltda-zexter-plano-r2000', 'responsável': 'GABRIELA', 'CD':'ES'},
    'ZEXTER':	{'url':'https://trello.com/c/ymplCym8/12-zexter-plano-r2000', 'responsável': 'GABRIELA', 'CD':'ES'},
    # EDUARDA
    'TL PROD NATURAIS':	{'url':'https://trello.com/c/YjtpOyhH/338-tl-produtos-naturais-plano-r-2600', 'responsável': 'EDUARDA', 'CD':'SC'},
    'SQUADRA DIG':	{'url':'https://trello.com/c/0j9AExBR/378-squadra-dig', 'responsável': 'EDUARDA', 'CD':'SC'},
    'DIETOX 30':	{'url':'https://trello.com/c/4UQwd49t/219-dietox-30-plano-r2500', 'responsável': 'EDUARDA', 'CD':'SC'},
    'WEPARTNER':	{'url':'https://trello.com/c/ACsHHzcp/350-wepartner-ltda-plano-r2500', 'responsável': 'EDUARDA', 'CD':'SC'},
    'G&J':	{'url':'https://trello.com/c/5ilXnpkB/387-gbn-gj-ecom-ltda-gbn-planor2600', 'responsável': 'EDUARDA', 'CD':'SC'},
    'REVITAL':	{'url':'https://trello.com/c/S9YJqz4v/304-revittal-all-natural-plano-r2400', 'responsável': 'EDUARDA', 'CD':'SC'},
    'MY IT':	{'url':'https://trello.com/c/XiE56MbG/322-my-it-r2600', 'responsável': 'EDUARDA', 'CD':'SP'},
    'ERETRINA':	{'url':'https://trello.com/c/VIAjx9Ym/346-eretrina-plano-r26oo', 'responsável': 'EDUARDA', 'CD':'SP'},
    'SAVE NUTRI':	{'url':'https://trello.com/c/l4a0xYvT/262-save-nutri-plano-r2800', 'responsável': 'EDUARDA', 'CD':'SP'},
    'GE':	{'url':'https://trello.com/c/DLYcT2Lk/306-ge-comércio-plano-r2600', 'responsável': 'EDUARDA', 'CD':'SP'},
    'DAPLOS':	{'url':'https://trello.com/c/yLgYWXlo/227-daplos-plano-r2400', 'responsável': 'EDUARDA', 'CD':'SP'},
    'FLUXO MIDIA':	{'url':'https://trello.com/c/7sMu4slf/365-fluxo-midia', 'responsável': 'EDUARDA', 'CD':'SP'},
    # INGRID
    '9BRAND':	{'url':'https://trello.com/c/JzF1nFSZ/108-9brand-plano-custo-30', 'responsável': 'INGRID', 'CD':'SC'},
    'RTJ':	{'url':'https://trello.com/c/ABllaD2S/339-rtj-empreendimentos-plano-r-2600', 'responsável': 'INGRID', 'CD':'SC'},
    'NEOVITTA / OTIMIZZA':	{'url':'https://trello.com/c/kFGh1JX3/132-otimizza-plano-custo-30', 'responsável': 'INGRID', 'CD':'SC'},
    'NUTRIDOMINUS':	{'url':'https://trello.com/c/NB4WFhwB/375-nutri-domminus-plano-r2600', 'responsável': 'INGRID', 'CD':'SC'},
    'ENERGY LIFE':	{'url':'https://trello.com/c/hdIMz0HV/393-energy-life', 'responsável': 'INGRID', 'CD':'ES'},
    'CAPS BOOK':	{'url':'https://trello.com/c/EslWZ2pk/327-caps-book-xtron-caps-plano-r2400', 'responsável': 'INGRID', 'CD':'SP'},
    'FREEDOM':	{'url':'https://trello.com/c/BXDno4uG/353-freedom-digital-ltda', 'responsável': 'INGRID', 'CD':'SP'},
    'MUSCLE MAGIC':	{'url':'https://trello.com/c/0riPDfEP/299-muscle-magic-plano-r2600', 'responsável': 'INGRID', 'CD':'SP'},
    'DOSI':	{'url':'https://trello.com/c/h3BG8G6H/286-dosi-plano-r2800', 'responsável': 'INGRID', 'CD':'SP'},
    'GUARANI':	{'url':'https://trello.com/c/TxYxFrFx/371-guarani', 'responsável': 'INGRID', 'CD':'SP'},
    'UNLOCKING':	{'url':'https://trello.com/c/S7TDr9OW/376-unlocking-plano-r2600', 'responsável': 'INGRID', 'CD':'SP'},
    'KAWABUNGA':	{'url':'https://trello.com/c/AUEtbVyP/216-kawabunga-custo20', 'responsável': 'INGRID', 'CD':'SP'},
    'ORÁCULO':	{'url':'https://trello.com/c/92kIgwvy/298-oráculo-plano-r2600', 'responsável': 'INGRID', 'CD':'SP'},
    'MATED':	{'url':'https://trello.com/c/q4BENj7q/357-mated', 'responsável': 'INGRID', 'CD':'SC'},
}

Outros_links = {
    'Novo Endereço':	{'url':'https://trello.com/c/8GGLLrIa/287-novo-endereço'},
    'Emails':	{'url':'https://trello.com/c/KDf2kME8/34-login-e-mail-expedição'},
    'Emails Colaboradores':	{'url':'https://trello.com/c/xtApAgjX/68-e-mail-colaboradores-goldlog'},
    'Acessos Portal':	{'url':'https://trello.com/c/YPKRGbR6/271-acesso-portal-box'},
    'Abrir PI':	{'url':'https://trello.com/c/9WNb0Whn/383-informações-para-abrir-pi'},
    'Formulario novas empresas':	{'url':'https://docs.google.com/spreadsheets/d/13Ivq0l0ueMB6GjO0xr6umLx7qHMvPJRAomjgxf3CunE/edit?resourcekey#gid=1485694145'},
    'FAQ':	{'url':'https://docs.google.com/document/d/1J5WdtliaF7o2KHvc30ibSB7rfNBjeWWW/edit'},
    'PLANILHA PARA CANCELAMENTOS(8TROPIA)':	{'url':'https://docs.google.com/spreadsheets/d/18GHl1KU512Nv9E8kDotSW5fbW24ye_QraWubBR1tIc0/edit#gid=1879777199'},
    'DEMANDAS TI':	{'url':'https://trello.com/b/YNrG7DW7/demandas'},
    'NOTAS SC': {'url': 'https://drive.google.com/drive/folders/1MS70MEIFDuhSfJD7CS08ZjrfHang73t6'}


}


