"""Create tables

Revision ID: 792fc1bb0b3d
Revises: cfb8203448c3
Create Date: 2024-03-12 16:46:30.833740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '792fc1bb0b3d'
down_revision = 'cfb8203448c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('task')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=50), nullable=False),
    sa.Column('task', sa.VARCHAR(length=100), nullable=False),
    sa.Column('data', sa.VARCHAR(length=20), nullable=False),
    sa.Column('observation', sa.VARCHAR(length=255), nullable=True),
    sa.Column('qtd', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('note')
    # ### end Alembic commands ###
